### ISSUE TITLE
More Discourse Attributes

### ISSUE THREAD

**Issue by MarcoRemy** [fmarco76/DiscourseSSO#2]
Hi Marco,

is it possible to use additional Discourse attributes? Those mentioned by the official [documentation](https://meta.discourse.org/DiscourseSSO/sso/auth).

Now your `DISCOURSE_USER_MAP` setting has four attributes. What about the others:
- avatar_url
- about_me
- admin
- moderator
- suppress_welcome_message

I tried them already but with no success. It would be great to control moderators and admins by the auth provider.

Regards

**Comment by fmarco76** [comment]
Thanks @NyroTheCat,

adding other attributes in the map requires some changes in sso.py. This currently read only the already specified attributes and should be extended to use also the others. Just few lines of code.

I am considering this issue for a future release.
